// Code generated by protoc-gen-go. DO NOT EDIT.
// source: solver.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SolveRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    int32    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolveRequest) Reset()         { *m = SolveRequest{} }
func (m *SolveRequest) String() string { return proto.CompactTextString(m) }
func (*SolveRequest) ProtoMessage()    {}
func (*SolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{0}
}

func (m *SolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolveRequest.Unmarshal(m, b)
}
func (m *SolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolveRequest.Marshal(b, m, deterministic)
}
func (m *SolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolveRequest.Merge(m, src)
}
func (m *SolveRequest) XXX_Size() int {
	return xxx_messageInfo_SolveRequest.Size(m)
}
func (m *SolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolveRequest proto.InternalMessageInfo

func (m *SolveRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *SolveRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *SolveRequest) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

type SolveResponse struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    int32    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	Answer               string   `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolveResponse) Reset()         { *m = SolveResponse{} }
func (m *SolveResponse) String() string { return proto.CompactTextString(m) }
func (*SolveResponse) ProtoMessage()    {}
func (*SolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{1}
}

func (m *SolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolveResponse.Unmarshal(m, b)
}
func (m *SolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolveResponse.Marshal(b, m, deterministic)
}
func (m *SolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolveResponse.Merge(m, src)
}
func (m *SolveResponse) XXX_Size() int {
	return xxx_messageInfo_SolveResponse.Size(m)
}
func (m *SolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolveResponse proto.InternalMessageInfo

func (m *SolveResponse) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *SolveResponse) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *SolveResponse) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *SolveResponse) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func init() {
	proto.RegisterType((*SolveRequest)(nil), "api.SolveRequest")
	proto.RegisterType((*SolveResponse)(nil), "api.SolveResponse")
}

func init() { proto.RegisterFile("solver.proto", fileDescriptor_7779dcc6dfedf133) }

var fileDescriptor_7779dcc6dfedf133 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0xcf, 0x29,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe0,
	0xe2, 0x09, 0x06, 0x09, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x70, 0x31, 0x26,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x26, 0x82, 0x78, 0x49, 0x12, 0x4c, 0x10, 0x5e,
	0x12, 0x88, 0x97, 0x2c, 0xc1, 0x0c, 0xe1, 0x25, 0x2b, 0x05, 0x72, 0xf1, 0x42, 0x75, 0x16, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x12, 0xaf, 0x55, 0x48, 0x8c, 0x8b, 0x2d, 0x31, 0xaf, 0xb8, 0x3c, 0xb5,
	0x48, 0x82, 0x45, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x33, 0xb2, 0xe2, 0x62, 0x03, 0x1b, 0x59,
	0x24, 0x64, 0xc0, 0xc5, 0x0a, 0x66, 0x09, 0x09, 0xea, 0x25, 0x16, 0x64, 0xea, 0x21, 0x3b, 0x51,
	0x4a, 0x08, 0x59, 0x08, 0x62, 0xb7, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x53, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x73, 0x2a, 0x64, 0xe4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Solver service

type SolverClient interface {
	Solve(ctx context.Context, in *SolveRequest, opts ...client.CallOption) (*SolveResponse, error)
}

type solverClient struct {
	c           client.Client
	serviceName string
}

func NewSolverClient(serviceName string, c client.Client) SolverClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "api"
	}
	return &solverClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *solverClient) Solve(ctx context.Context, in *SolveRequest, opts ...client.CallOption) (*SolveResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Solver.Solve", in)
	out := new(SolveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Solver service

type SolverHandler interface {
	Solve(context.Context, *SolveRequest, *SolveResponse) error
}

func RegisterSolverHandler(s server.Server, hdlr SolverHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Solver{hdlr}, opts...))
}

type Solver struct {
	SolverHandler
}

func (h *Solver) Solve(ctx context.Context, in *SolveRequest, out *SolveResponse) error {
	return h.SolverHandler.Solve(ctx, in, out)
}
